export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const UPDATE_DEVICE_PROFILE = "UPDATE_DEVICE_PROFILE";

//Employee Related Actions
export const GET_ABSENCE_RELATED_INFO_SUCCESS = "GET_ABSENCE_RELATED_INFO_SUCCESS";
export const GET_ABSENCE_TYPES_SUCCESS = "GET_ABSENCE_TYPES_SUCCESS";
export const GET_ABSENCES_SUMMARY_SUCCESS = "GET_ABSENCES_SUMMARY_SUCCESS";
export const GET_MY_ABSENCE_SUCCESS = "GET_MY_ABSENCE_SUCCESS";
export const GET_ABSENCE_REQUEST_SUCCESS = "GET_ABSENCE_REQUEST_SUCCESS";
export const GET_CALCULATED_DAYS_SUCCESS = "GET_CALCULATED_DAYS_SUCCESS"; //unused?


//Manager Related Actions
export const GET_MANAGER_PENDING_SUCCESS = "GET_MANAGER_PENDING_SUCCESS";
export const GET_EMPLOYEE_RELATED_INFO_SUCCESS = "GET_EMPLOYEE_RELATED_INFO_SUCCESS";



